#!/usr/bin/env python3

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Benchy benchmarking tool."""

import argparse
import logging

from lib import aggregate
from lib import build
from lib import common
from lib import create
from lib import device
from lib import run
from lib import workload


def create_parser():
    """Create command line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.set_defaults(func=None)

    parser.add_argument('--debug',
                        action='store_true',
                        help='enable debug logs')

    subparsers = parser.add_subparsers(dest='command', required=True)

    create.add_subparser(subparsers)
    build.add_subparser(subparsers)
    device.add_subparser(subparsers)
    run.add_subparser(subparsers)
    workload.add_subparser(subparsers)
    aggregate.add_subparser(subparsers)

    return parser

def main():
    """benchy benchmarking main dispatch."""
    parser = create_parser()
    args = parser.parse_args()

    logging.basicConfig(
        format=common.LOGGING_FORMAT,
        datefmt=common.LOGGING_DATE_FORMAT,
        level=logging.DEBUG if args.debug else logging.INFO)

    if args.func:
        args.func(args)

if __name__ == "__main__":
    main()
