// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package main

// Code generated by gen/gen_amd_pci_ids_map.go. DO NOT EDIT.

// Run the following code to regenerate it.
// go run cmd/hardware_probe/gen/gen_amd_pci_ids_map.go --mesaLib=r300_pci_ids.h:r600_pci_ids.h:radeonsi_pci_ids.h --output=cmd/hardware_probe/amd_pci_ids.go --function=getAMDPCIIDMap
// gofmt -w -d -s cmd/hardware_probe/amd_pci_ids.go

func getAMDPCIIDMap() map[string]string {
	return map[string]string{
		// This is the manual mapping defined in cmd/hardware_probe/gen/gen_amd_pci_ids_map.go
		// Update it if mesa/kernel fails to import the desired PCI ID mapping.

		"0x1506": "gc_10_3_7",

		// This is mapping imported from mesa and kernel repository.

		"0x15d8": "picasso",
		"0x15dd": "picasso",
		"0x15e7": "cezanne",
		"0x1636": "cezanne",
		"0x1638": "cezanne",
		"0x164c": "cezanne",
		"0x9870": "carrizo",
		"0x9874": "carrizo",
		"0x9875": "carrizo",
		"0x9876": "carrizo",
		"0x9877": "carrizo",
		"0x98e4": "stoney",
	}
}
