// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package main

// Code generated by gen/gen_pci_ids_map.go. DO NOT EDIT.

// Run the following code to regenerate it.
// go run cmd/hardware_probe/gen/gen_pci_ids_map.go --library=virtio_gpu_pci_ids.h:vmwgfx_pci_ids.h --output=cmd/hardware_probe/vm_pci_ids.go --funcName=getVMPCIIDMap
// gofmt -w -d -s cmd/hardware_probe/vm_pci_ids.go

func getVMPCIIDMap() map[string]string {
	return map[string]string{

		"0x0010": "virtio",
		"0x0405": "vmware",
		"0x0406": "vmware",
		"0x1050": "virtio",
	}
}
