// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package utils

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	gen_db "go.chromium.org/chromiumos/graphics-utils-go/trace_profiling/cmd/gen_db_result/common"
	"go.chromium.org/chromiumos/graphics-utils-go/trace_profiling/cmd/harvest/config"
	remote "go.chromium.org/chromiumos/graphics-utils-go/trace_profiling/cmd/profile/remote"

	"github.com/google/uuid"
	db "go.chromium.org/chromiumos/config/go/api/test/results/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

const (
	// Tool to run on the device to get device info.
	getInfoToolName = "get_device_info"

	// Templates used to generate filename for protobufs in conjunction with
	// function filenameFromTemplate.
	machinePbFileTemplate            = "machine_info_[[name]].json"
	targetSoftwareInfoPbFileTemplate = "software_info_[[exec-env]]_[[name]].json"
	hostSoftwareInfoPbFileTemplate   = "software_info_host_[[name]].json"
)

// DeviceInfoTool represents the tool used to get information from a device
// reachable through SSH.
type DeviceInfoTool struct {
	config      *config.DeviceInfoToolConfig // Tool config.
	execEnv     string                       // The exec env, e.g. "crostini".
	machineName string                       // Unique device ID.

	// SSH and tunneling parameters from the profile configuration.
	targetSSHParams *remote.SSHParams
	tunnelParams    *remote.TunnelParams

	// SSH connections
	// The target SSH is whatever device is defined by the SSH parameters. If tunnel
	// parameters are defined, it usually is a VM or crouton device. Otherwise, it's
	// the host OS. The hostOsSSH is always the Chrome-OS host. It's only used when
	// it's different from the target SSH.
	targetSSH    *remote.SSHTarget
	hostOsSSH    *remote.SSHTarget
	targetTunnel *remote.Tunnel

	// Software- and machine-info protobuf gathered from the device.
	machinePb        *db.Machine
	targetSoftwarePb *db.SoftwareConfig
	parentSoftwarePb *db.SoftwareConfig

	verbose bool
}

// NewDeviceInfoTool create and returns a new DeviceInfoTool objects.
func NewDeviceInfoTool(verbose bool) *DeviceInfoTool {
	return &DeviceInfoTool{
		verbose: verbose,
	}
}

// Setup is used to setup DeviceInfoTool with the device's SSH parameters.
// It must be invoked before calling Run. It is ok to re-use a DeviceInfoTool
// object multiple times by calling Setup/Run in tandem.
func (dit *DeviceInfoTool) Setup(
	config *config.DeviceInfoToolConfig,
	execEnv string,
	machineName string,
	sshParams *remote.SSHParams,
	tunnelParams *remote.TunnelParams) error {

	dit.config = config
	dit.execEnv = execEnv
	dit.machineName = machineName
	dit.targetSSHParams = sshParams
	dit.tunnelParams = tunnelParams

	dit.hostOsSSH = nil
	dit.targetSSH = nil
	dit.targetTunnel = nil

	dit.machinePb = nil
	dit.targetSoftwarePb = nil
	dit.parentSoftwarePb = nil

	if machineName == "" {
		dit.printMachineNameInfoRequirement()
		return fmt.Errorf("no machine name provided in config file")
	}

	return nil
}

// Run runs DeviceInfoTool with the current configuration to collect device
// information from an attached device.
func (dit *DeviceInfoTool) Run() error {
	defer func() {
		if dit.hostOsSSH != nil {
			dit.hostOsSSH.Disconnect()
		}
		if dit.targetSSH != nil {
			dit.targetSSH.Disconnect()
		}
		if dit.targetTunnel != nil {
			dit.targetTunnel.Close()
		}
	}()

	// If the Machine config is defined and enabled, collect machine info.
	if dit.config.Machine != nil && dit.config.Machine.Enabled {
		machinePb, err := dit.collectMachineInfo()
		dit.machinePb = machinePb
		if err != nil {
			return err
		}
	}

	// If the Software config is defined and enabled, collect software info.
	if dit.config.Software != nil && dit.config.Software.Enabled {
		// Generate a base software ID. Software IDs for the parent environments are
		// generated by appending the exec env to the base ID.
		softwareId := uuid.New().String()

		softwarePb, err := dit.collectTargetSoftwareInfo(softwareId)
		dit.targetSoftwarePb = softwarePb
		if err != nil {
			return err
		}

		// TODO(gwink): In environments such as Crostini, also-run-on-parent should imply
		// running on the entire chain of parent environments, namely Termina and the
		// host Chrome OS.

		if dit.config.Software.AlsoRunOnParent {
			softwarePb, err := dit.collectParentSoftwareInfo(softwareId + "_host")
			dit.parentSoftwarePb = softwarePb
			if err != nil {
				return err
			}
		}
	}

	return dit.writeAndUploadProtobufs()
}

// Write all the collected protobufs to files and optionally upload them to the result DB.
func (dit *DeviceInfoTool) writeAndUploadProtobufs() error {
	// Ensure the destination dir exists.
	if dit.config.ProtoBufsOutputDir != "" {
		if err := os.MkdirAll(dit.config.ProtoBufsOutputDir, os.ModePerm); err != nil {
			return err
		}
	}

	if err := dit.writeAndUploadMachineProtobuf(); err != nil {
		return err
	}

	return dit.writeAndUploadSoftwareProtobufs()
}

// Write to file and upload the machine-info protobuf.
func (dit *DeviceInfoTool) writeAndUploadMachineProtobuf() error {
	if dit.machinePb != nil {
		pbFilePath := dit.getPbFilePath(dit.config.ProtoBufsOutputDir, machinePbFileTemplate)
		uploadMode := dit.config.Machine.UploadToDb
		needUpdate := dit.checkIfMachineInfoHasChanged(dit.machinePb, pbFilePath)
		if needUpdate {
			fmt.Printf("Updating machine-info pb\n")
			err := dit.writeProtoBufToFile(dit.machinePb, pbFilePath)
			if err != nil {
				return fmt.Errorf("could not save machine-info protobuf to file for %s: %s",
					dit.execEnv, err.Error())
			}
		}
		if uploadMode == config.UploadModeAlways {
			if err := dit.uploadPbToResultDb(pbFilePath, "Machine"); err != nil {
				return fmt.Errorf("could not upload protobuf %s to DB: err=%s",
					pbFilePath, err.Error())
			}
		}
	}

	return nil
}

// Write to file and upload the software-config protobufs.
func (dit *DeviceInfoTool) writeAndUploadSoftwareProtobufs() error {
	// Start with the parent software-config protobuf. Its ID will be stored in the
	// target software-config protobuf and may require that it is updated.
	parentSoftwareId, err := dit.writeAndUploadSoftwareConfigPb(
		dit.parentSoftwarePb, hostSoftwareInfoPbFileTemplate)
	if err != nil {
		return err
	}

	dit.targetSoftwarePb.Parent = parentSoftwareId
	_, err = dit.writeAndUploadSoftwareConfigPb(
		dit.targetSoftwarePb, targetSoftwareInfoPbFileTemplate)

	return err
}

// Write a single software-config protobuf to file and optionally upload it to
// the result DB. Return its protobuf ID and any error.
func (dit *DeviceInfoTool) writeAndUploadSoftwareConfigPb(
	softwarePb *db.SoftwareConfig, pbFileTemplate string) (*db.SoftwareConfigId, error) {

	if softwarePb == nil {
		return nil, nil
	}

	uploadMode := dit.config.Software.UploadToDb
	pbFilePath := dit.getPbFilePath(dit.config.ProtoBufsOutputDir, pbFileTemplate)
	oldSoftwarePbFromFile := dit.readSoftwareConfigPbFromFile(pbFilePath)
	needUpdate := dit.checkIfSoftwareInfoHasChanged(softwarePb, oldSoftwarePbFromFile)

	// Retain the ID for this protobuf, either the old one from the file or the
	// new one if the protobuf is updated.
	var pbSoftwareId *db.SoftwareConfigId
	if oldSoftwarePbFromFile != nil {
		pbSoftwareId = oldSoftwarePbFromFile.GetId()
	}

	if needUpdate {
		pbSoftwareId = softwarePb.GetId()
		err := dit.writeProtoBufToFile(softwarePb, pbFilePath)
		if err != nil {
			return nil, fmt.Errorf("could not save software-info protobuf to file %s: %s",
				pbFilePath, err.Error())
		}
	}

	if uploadMode == config.UploadModeAlways {
		if err := dit.uploadPbToResultDb(pbFilePath, "SoftwareConfig"); err != nil {
			return nil, fmt.Errorf("could not upload protobuf %s to DB: err=%s",
				pbFilePath, err.Error())
		}
	}

	return pbSoftwareId, nil
}

// Upload the protobuf in file with path pbFilePath to the Result DB. Arg pbType is
// protobuf type and is passed as option --message to the upload script. It should be one
// of "Machine", "ResultList", "SoftwareConfig" or "TraceList".
func (dit *DeviceInfoTool) uploadPbToResultDb(pbFilePath string, pbType string) error {
	uploadScript := dit.config.UploadScript
	if uploadScript == "" {
		uploadScript = "bq_insert_pb.py"
	}

	dit.printIfVerbose("Uploading PB %s to result DB.... ", pbFilePath)

	cmd := exec.Command(uploadScript, "--deduplicate", "--message", pbType, pbFilePath)

	result, err := cmd.CombinedOutput()
	if err != nil {
		dit.printIfVerbose("failed.\n")
		return fmt.Errorf("exec failed: %s, err = %s", result, err)
	}

	dit.printIfVerbose("done.\n")
	return nil
}

// Return whether the machine-info in machinePb is different from the one found in the
// file at pbFilePath. The create-time field is ignored for this comparison. Always return
// true if the file doesn't exist.
func (dit *DeviceInfoTool) checkIfMachineInfoHasChanged(
	machinePb *db.Machine, pbFilePath string) bool {

	// Load the reference PB from file.
	var pbFromFile db.Machine
	if err := gen_db.ReadProtoFromFile(pbFilePath, &pbFromFile); err != nil {
		fmt.Printf("No machine-info PB file\n")
		return true
	}

	// The create-time timestamp is irrelevant in the comparison. Zero it in both PBs.
	savedTimeStamp := machinePb.GetCreateTime()
	machinePb.CreateTime = nil
	pbFromFile.CreateTime = nil

	// PB struct have internal fields that make deep-comparisons difficult. Instead,
	// convert both PBs to string and compare the strings.
	str1, _ := proto.Marshal(machinePb)
	str2, _ := proto.Marshal(&pbFromFile)
	eq := bytes.Equal(str1, str2)

	if !eq {
		fmt.Printf("\n\n Machine info changed:\n\n%s\n\n%s\n\n", str1, str2)
	}

	// Restore the create-time timestamp in the input PB.
	machinePb.CreateTime = savedTimeStamp

	return !eq
}

// Read a software-config protobuf from file. Return nil if the file cannot be read.
func (dit *DeviceInfoTool) readSoftwareConfigPbFromFile(pbFilePath string) *db.SoftwareConfig {
	var pbFromFile db.SoftwareConfig
	if err := gen_db.ReadProtoFromFile(pbFilePath, &pbFromFile); err != nil {
		return nil
	}

	return &pbFromFile
}

// Return whether the software configs in newSoftwarePb and oldSoftwarePb are identical.
func (dit *DeviceInfoTool) checkIfSoftwareInfoHasChanged(
	newSoftwarePb, oldSoftwarePb *db.SoftwareConfig) bool {

	// If there's no old software-config protobuf then we definitely need to update it.
	if oldSoftwarePb == nil {
		return true
	}

	// The create-time timestamp is irrelevant in the comparison. Zero it in both PBs.
	newTimeStamp := newSoftwarePb.GetCreateTime()
	oldTimeStamp := oldSoftwarePb.GetCreateTime()
	newSoftwarePb.CreateTime = nil
	oldSoftwarePb.CreateTime = nil

	// Likewise with the protobuf ID. A new uuid is generated each time. If the rest of the
	// buffers match, we can ignore it.
	newPbId := newSoftwarePb.GetId()
	oldPbId := oldSoftwarePb.GetId()
	newSoftwarePb.Id = nil
	oldSoftwarePb.Id = nil

	// PB struct have internal fields that make deep-comparisons difficult. Instead,
	// convert both PBs to string and compare the strings.
	str1, _ := proto.Marshal(newSoftwarePb)
	str2, _ := proto.Marshal(oldSoftwarePb)
	eq := bytes.Equal(str1, str2)

	// Restore the zero-out fields in the input PB.
	newSoftwarePb.CreateTime = newTimeStamp
	newSoftwarePb.Id = newPbId
	oldSoftwarePb.CreateTime = oldTimeStamp
	oldSoftwarePb.Id = oldPbId

	return !eq
}

// Return the full file path to the file with the given template and parent directory dir.
func (dit *DeviceInfoTool) getPbFilePath(dir, fileTemplate string) string {
	filename := dit.filenameFromTemplate(fileTemplate)
	if dir != "" {
		filename = filepath.Join(dir, filename)
	}

	return filename
}

// Write a single protobuf to file. The file name is derived from the file template.
// If the template is the empty string, no output takes place. The output file
// format is determined by the filename extension and may be either JSON or raw
// protobuf.
func (dit *DeviceInfoTool) writeProtoBufToFile(pb proto.Message, pbFilePath string) error {
	dit.printIfVerbose("Writing protobuf to %s\n", pbFilePath)
	return gen_db.WriteProtobuf(pb, pbFilePath)
}

// Return a filename derived from a template. Recognized template placeholders are
// [[name]] for the machine name, [[exec-env]] for the execution environment (e.g.
// "crostini", [[utc-date]] and [[utc-time]].)
func (dit *DeviceInfoTool) filenameFromTemplate(fileTemplate string) string {
	filename := strings.ReplaceAll(fileTemplate, "[[name]]", dit.machineName)
	filename = strings.ReplaceAll(filename, "[[exec-env]]", dit.execEnv)
	filename = strings.ReplaceAll(filename, "[[utc-date]]", GetUTCDateString())
	return strings.ReplaceAll(filename, "[[utc-time]]", GetUTCTimeString())
}

// Collect the machine-info from the device reachable through SSH by running
// the get_device_info tool on that device. On success, a machine-info
// protobuf is returned. The target device for machine-info is always the host OS.
func (dit *DeviceInfoTool) collectMachineInfo() (*db.Machine, error) {
	// Get a SSH connection to the host OS (not a VM nor crouton).
	ssh, err := dit.getHostOsDeviceSSH()
	if err != nil {
		return nil, err
	}

	// Create a temp folder on device for binaries and data.
	tmpDir, err := ssh.MkTempDir("./")
	if err != nil {
		return nil, err
	}
	defer ssh.DelFile(tmpDir)

	// If the path to the get_device_info tool in the config is not empty, then
	// copy the tool binaries to the device.
	toolPath := ""
	if dit.config.GetDeviceInfoBinPath != "" {
		toolPath, err = dit.installToolOnSSHTarget(ssh, tmpDir)
		if err != nil {
			return nil, err
		}
	}

	// Run the tool to get the machine info.
	output, err := dit.runToolForMachineInfo(ssh, toolPath)
	if err != nil {
		return nil, err
	}

	// Take output from running the tool, which should be JSON, and create a
	// machine-info protobuf.
	machineInfo := db.Machine{}
	err = protojson.Unmarshal([]byte(output), &machineInfo)
	return &machineInfo, err
}

// Collect and return the software-info protobuf data from the target device.
func (dit *DeviceInfoTool) collectTargetSoftwareInfo(id string) (*db.SoftwareConfig, error) {
	// Get a SSH connection to the target device.
	ssh, err := dit.getTargetDeviceSSH()
	if err != nil {
		return nil, err
	}

	return dit.collectSoftwareInfoFromSSHTarget(ssh, id)
}

// Collect the software-info protobuf data from the host-OS. If tunnel SSH parameters
// are not defined, the host OS is the same as the target device. In that case, this
// function doesn't do anything.
func (dit *DeviceInfoTool) collectParentSoftwareInfo(id string) (*db.SoftwareConfig, error) {
	if dit.tunnelParams == nil {
		dit.printIfVerbose("Target %s: OS has no parent, not collecting parent software info.\n",
			dit.execEnv)
		return nil, nil
	}

	// Get a SSH connection to the actual device (not a VM nor crouton).
	ssh, err := dit.getHostOsDeviceSSH()
	if err != nil {
		return nil, err
	}

	return dit.collectSoftwareInfoFromSSHTarget(ssh, id)
}

// Collect and return the software-info protobuf from the given SSH target.
func (dit *DeviceInfoTool) collectSoftwareInfoFromSSHTarget(
	ssh *remote.SSHTarget, id string) (*db.SoftwareConfig, error) {

	// Create a temp folder on target for binaries and data.
	tmpDir, err := ssh.MkTempDir("./")
	if err != nil {
		return nil, err
	}
	defer ssh.DelFile(tmpDir)

	// If the path to the get_device_info tool in the config is not empty, then
	// copy the tool binaries to the device.
	toolPath := ""
	if dit.config.GetDeviceInfoBinPath != "" {
		toolPath, err = dit.installToolOnSSHTarget(ssh, tmpDir)
		if err != nil {
			return nil, err
		}
	}

	// Run the tool to get the machine info.
	output, err := dit.runToolForSoftwareInfo(ssh, toolPath, id)
	if err != nil {
		return nil, err
	}

	// Load output from running the tool, which should be in JSON form, into a
	// protobuf object.
	softwareInfo := db.SoftwareConfig{}
	err = protojson.Unmarshal([]byte(output), &softwareInfo)
	return &softwareInfo, err
}

// Return a SSH connection to the Chrome-OS host.
func (dit *DeviceInfoTool) getHostOsDeviceSSH() (*remote.SSHTarget, error) {
	if dit.hostOsSSH != nil {
		return dit.hostOsSSH, nil
	}

	// If tunneling parameters are not defined, the target device is the same as
	// the host OS.
	if dit.tunnelParams == nil {
		return dit.getTargetDeviceSSH()
	}

	sshParams := &dit.tunnelParams.Server
	if sshParams == nil {
		return nil, fmt.Errorf("no SSH config available for target device")
	}

	var err error
	dit.hostOsSSH, err = remote.CreateSSHTargetWithParams(sshParams)
	if err != nil {
		return nil, err
	}

	err = dit.hostOsSSH.Connect()
	return dit.hostOsSSH, err
}

// Return a SSH connection to the target device, such as the Crostini VM device.
// However, when SSH-tunnel parameters are not specified, the target device is the
// Chrome-OS host.
func (dit *DeviceInfoTool) getTargetDeviceSSH() (*remote.SSHTarget, error) {
	if dit.targetSSH != nil {
		return dit.targetSSH, nil
	}

	var err error
	tunnelOkChan := make(chan bool, 1)
	if dit.tunnelParams != nil {
		dit.targetTunnel, err = remote.CreateTunnel(dit.tunnelParams)
		if err != nil {
			return nil, fmt.Errorf("could not tunnel to device: err = %s", err.Error())
		}

		go func() {
			err = dit.targetTunnel.BeginTunneling(tunnelOkChan)
		}()
	} else {
		// It's ok if there's no tunnel. It most likely means we're SSH'ing directly
		// to the host OS. Just pretend that the tunnel is ready.
		tunnelOkChan <- true
	}

	// Wait for tunnel to be ready.
	tunnelOk := <-tunnelOkChan
	if !tunnelOk {
		return nil, err
	}

	dit.targetSSH, err = remote.CreateSSHTargetWithParams(dit.targetSSHParams)
	if err != nil {
		return nil, fmt.Errorf("could not SSH into target device: err = %s", err.Error())
	}

	err = dit.targetSSH.Connect()
	return dit.targetSSH, err
}

// Install the get_device_info tool on the SSH target. Return the full path to
// the tool's binary.
func (dit *DeviceInfoTool) installToolOnSSHTarget(
	ssh *remote.SSHTarget, dir string) (string, error) {

	dstFilename := filepath.Join(dir, getInfoToolName)
	dit.printIfVerbose("Installing tool on device: %s\n", dstFilename)
	err := ssh.SendFile(dit.config.GetDeviceInfoBinPath, dstFilename, "0755")
	return dstFilename, err
}

// Run the get_device_info tool on the target device to get machine info.
func (dit *DeviceInfoTool) runToolForMachineInfo(
	ssh *remote.SSHTarget, toolPath string) (string, error) {

	// If toolpath is "", we did not install the tool. Instead, we assume it is
	// pre-installed and available in PATH, so that it can be invoked by its name.
	if toolPath == "" {
		toolPath = getInfoToolName
	}

	// Setup cmd-line options as mandated by the machine configuration.
	cmd := fmt.Sprintf("%s machine-info", toolPath)
	if dit.machineName != "" {
		cmd = cmd + " -name " + dit.machineName
	}
	if dit.config.Owner != "" {
		cmd = cmd + " -owner " + dit.config.Owner
	}

	dit.printIfVerbose("Run cmd on device: \"%s\"\n", cmd)

	return ssh.RunCmd(cmd)
}

func (dit *DeviceInfoTool) runToolForSoftwareInfo(
	ssh *remote.SSHTarget, toolPath string, id string) (string, error) {

	// If toolpath is "", we did not install the tool. Instead, we assume it is
	// pre-installed and available in PATH, so that it can be invoked by its name.
	if toolPath == "" {
		toolPath = getInfoToolName
	}

	// Setup cmd-line options as mandated by the machine configuration.
	cmd := fmt.Sprintf("%s software-info", toolPath)
	if dit.config.Software.SkipPackages {
		cmd = cmd + " -skip-packages"
	}
	cmd = cmd + " -id " + id

	dit.printIfVerbose("Run cmd on device: \"%s\"\n", cmd)

	return ssh.RunCmd(cmd)
}

// If verbose mode is enabled, print the formatted string.
func (dit *DeviceInfoTool) printIfVerbose(format string, a ...interface{}) {
	if dit.verbose {
		fmt.Printf(format, a...)
	}
}

// Print useful information about the requirement for a unique machine name
// in the configuration file.
func (dit *DeviceInfoTool) printMachineNameInfoRequirement() {
	uuidMachineName := uuid.New().String()
	fmt.Fprintf(os.Stderr,
		"Error: A globally unique machine name must be provided in the configuration\n"+
			"file. You may use the uuid \"%s\", or something\n"+
			"like \"<ldap>-<asset ID>\", where the asset-ID is taken from the asset tag,\n"+
			"or you may create your own unique machine name. Once you have chosen a\n"+
			"machine name, enter it in the JSON config file under Device -> name \n"+
			"for device %s.\n", uuidMachineName, dit.execEnv)
}
