#!/bin/sh

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

usage() {
  cat <<EOD
Usage: $0 [OPTION]... [--] COMMAND ARGUMENTS

Options:
  --help              Displays this message.
  --cache CACHE_DIR   Mesa shader cache directory.
EOD
}

base="$(dirname "$0")/${base}"
basedir="${base%/*}"

while true; do
  case "$1" in
    --cache)
      cache="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    -*)
      echo "$0: invalid option: $1"
      usage
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

if [ -n "${cache}" ]; then
  export MESA_SHADER_CACHE_DIR="${cache}"
fi
exec "${basedir}/intel-shim" --gpu adl "$@"
