#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [[ "$1" = "--help" ]]; then
  echo "syntax: $0"
  echo "  [--ssh device]           IP of device or VM to trace (default" \
       "is local trace)"
  echo "  [-t duration_ms]         Duration to trace (default is until Ctrl+C)"
  echo "  [-o output_file]"
  echo "  [-b buffer_size_kb]      Size of trace buffer in KB"
  echo "  [-p /path/to/perfetto]   Path to perfetto tool if it's not in \$PATH"
  echo "  [-i period_ms]           Incremental update period in ms"
  echo "  [--no-ftrace]            Do not include ftrace sched data"
  echo "  [-d category] ...           Disabled categories"
  echo "  [category] [category] ...   Enabled categories"
  echo "examples:"
  echo "  $0 --ssh DUT                      trace on DUT until Ctrl C"
  echo "  $0 --ssh DUT -t 1000              trace for 1 second"
  echo "  $0 --ssh DUT virgls               include virgls category" \
       "(disabled-by-default)"
  echo "  $0 --ssh DUT -d \"*\" virgl gfx     only trace virgl and gfx"
  exit 1
fi

dut=''
time_ms=''
ftrace=true
categories=()
disabled_categories=()
now=$(date +"%Y-%m-%d_%H-%M-%S")
output_file=''
config_file="/tmp/perfetto-${RANDOM}.config"
perfetto=perfetto
incremental_update_period_ms=1000
buffer_size_kb=100000
fill_policy=RING_BUFFER

# Parse args

args=("$@")
num_args="${#args[@]}"
for (( i = 0; i < num_args; i++ )); do
  if [[ "${args[${i}]}" = "--ssh" ]]; then
    i=$((i+1))
    dut="${args[${i}]}"
  elif [[ "${args[${i}]}" = "-t" ]]; then
    i=$((i+1))
    time_ms="${args[${i}]}"
    fill_policy=DISCARD
  elif [[ "${args[${i}]}" = "-o" ]]; then
    i=$((i+1))
    output_file="${args[${i}]}"
  elif [[ "${args[${i}]}" = "-b" ]]; then
    i=$((i+1))
    buffer_size_kb="${args[${i}]}"
  elif [[ "${args[${i}]}" = "-p" ]]; then
    i=$((i+1))
    perfetto="${args[${i}]}"
  elif [[ "${args[${i}]}" = "-i" ]]; then
    i=$((i+1))
    incremental_update_period_ms="${args[${i}]}"
  elif [[ "${args[${i}]}" = "-d" ]]; then
    i=$((i+1))
    disabled_categories+=("${args[${i}]}")
  elif [[ "${args[${i}]}" = "--no-ftrace" ]]; then
    i=$((i+1))
    ftrace=false
  else
    categories+=("${args[${i}]}")
  fi
done

if [[ -z "${output_file}" ]]; then
  if [[ -z "${dut}" ]]; then
    output_file=./perfetto-trace-${now}
  else
    output_file=./${dut}-perfetto-trace-${now}
  fi
fi

# Write perfetto config file

cat >"${config_file}" <<EOL
buffers: {
  size_kb: ${buffer_size_kb}
  fill_policy: ${fill_policy}
}
buffers: {
  size_kb: 4000
  fill_policy: DISCARD
}
incremental_state_config: {
  clear_period_ms: ${incremental_update_period_ms}
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
        }
    }
}
EOL

if [[ "${ftrace}" = true ]]; then
  cat >>"${config_file}" <<EOL
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            # These parameters affect only the kernel trace buffer size and how
            # frequently it gets moved into the userspace buffer defined above.
            buffer_size_kb: 16384
            drain_period_ms: 250
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_process_exec"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_fork"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "sched/sched_process_hang"
            ftrace_events: "sched/sched_process_wait"
            ftrace_events: "sched/sched_switch"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "tracing_mark_write"
            ftrace_events: "thermal/thermal_temperature"
            ftrace_events: "thermal/cdev_update"
        }
    }
}
EOL
fi

cat >>"${config_file}" <<EOL
data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            meminfo_period_ms: 1000
            meminfo_counters: MEMINFO_MEM_TOTAL
            meminfo_counters: MEMINFO_MEM_FREE
            meminfo_counters: MEMINFO_MEM_AVAILABLE

            vmstat_period_ms: 1000
            vmstat_counters: VMSTAT_NR_FREE_PAGES
            vmstat_counters: VMSTAT_NR_ALLOC_BATCH
            vmstat_counters: VMSTAT_NR_INACTIVE_ANON
            vmstat_counters: VMSTAT_NR_ACTIVE_ANON

            stat_period_ms: 2500
            stat_counters: STAT_CPU_TIMES
            stat_counters: STAT_FORK_COUNT
        }
    }
}
data_sources: {
    config {
        name: "track_event"
        track_event_config: {
EOL

for (( i = 0; i < ${#categories[@]}; i++ ));
do
  echo "            enabled_categories: \"${categories[${i}]}\"" >> \
       "${config_file}"
done

for (( i = 0; i < ${#disabled_categories[@]}; i++ ));
do
  echo "            disabled_categories: \"${disabled_categories[${i}]}\"" >> \
       "${config_file}"
done

cat >>"${config_file}" <<EOL
        }
    }
}
EOL

if [[ -n "${time_ms}" ]]; then
  echo "duration_ms: ${time_ms}" >> "${config_file}"
else
  echo "Press Ctrl+C to stop tracing..."
fi

if [[ -z "${dut}" ]]; then
  # Kick off the perfetto command locally
  "${perfetto}" -c "${config_file}" --txt -o "${output_file}" || exit 1
else
  # Kick off the perfetto command on the DUT
  scp -q "${config_file}" "${dut}:${config_file}" || exit 1
  ssh "${dut}" '[[ -n $(pgrep traced) ]] || start traced' 2> /dev/null
  ssh -q -t "${dut}" "${perfetto}" -c "${config_file}" --txt -o \
      /tmp/perfetto-trace || exit 1
  scp -q "${dut}:/tmp/perfetto-trace" "${output_file}" && \
      ssh "${dut}" rm /tmp/perfetto-trace || exit 1
fi

echo "${output_file}"
